# Docs: https://numtide.github.io/devshell

[devshell]
# packages = [ # Search: https://search.nixos.org/packages
#   "curl",
# ]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments - https://github.com/numtide/devshell/"
